[package]
name = "solana-paylink-hello"
version = "0.1.0"
authors = ["tms1337 <faruk1337@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.9.0"
borsh = "0.9.1"

