[package]
name = "solana-paylink-hello"
version = "0.1.0"
authors = ["tms1337 <faruk1337@gmail.com>"]
edition = "2018"

[dependencies]
borsh = "0.9.2"
solana-program = "1.9.11"

[dev-dependencies]
solana-program-test = "1.9.11"
tokio = { version = "1.15.0", features = ["full"] }
